config/routes.rb
Moochip::Application.routes.draw do
  resources :articles

  match 'developers' => 'home#developers'
  match 'demo-raphael' => 'home#demo_raphael'
  match 'license' => 'home#license'
  

  root :to => 'home#index'

  match ':controller(/:action(/:id))(.:format)'
  
  match 'search(/:query)' => 'home#search'
end

app/models/article.rb
class Article < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @articles }
    end
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
    @article = Article.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @article }
    end
  end

  # GET /articles/new
  # GET /articles/new.json
  def new
    @article = Article.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @article }
    end
  end

  # GET /articles/1/edit
  def edit
    @article = Article.find(params[:id])
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(params[:article])

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render json: @article, status: :created, location: @article }
      else
        format.html { render action: "new" }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /articles/1
  # PUT /articles/1.json
  def update
    @article = Article.find(params[:id])

    respond_to do |format|
      if @article.update_attributes(params[:article])
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    respond_to do |format|
      format.html { redirect_to articles_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @title = 'moochip - home'
  end
  
  def developers
    @title = 'moochip - developers'
  end

  def demo_console
    @demo = 'console'
  end

  def demo_raphael
    @title = 'moochip - demo'
    @demo = 'raphael'
  end
  
  def license
	@license = """
	This work is licensed under the Creative Commons Attribution-ShareAlike 3.0 Unported License. To view a copy of this license, visit http://creativecommons.org/licenses/by-sa/3.0/ or send a letter to Creative Commons, 444 Castro Street, Suite 900, Mountain View, California, 94041, USA.
	"""
  end
  
  def search
	@query = params[:query]
	
	if (!@query or @query.empty?) then
		render :json => []
	end
	
	@words = @query.split(/\s+/).collect { |e| e.downcase }
	@word_combinations = []
	
	1.upto @words.size do |i|
		tmp = []
		p = @words.permutation(i).to_a
		
		p.each { |e| tmp += ['%' + e.join('%') + '%'] * 2 }
		
		@word_combinations << tmp
	end
	
	@word_combinations.flatten!
	
	Rails.logger.debug("Search query: #{ @query.inspect }")
	Rails.logger.debug("Word combinations: #{ @word_combinations.inspect }")
	
	@articles = Article.where((['lower(title) like ? or lower(body) like ?'] * (@word_combinations.size / 2)).join(' or '), *@word_combinations)
	
	Rails.logger.debug("Articles found: #{ @articles.inspect }")
	
	render :json => @articles
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing article</h1>

<%= render 'form' %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<h1>Listing articles</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Body</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @articles.each do |article| %>
  <tr>
    <td><%= article.title %></td>
    <td><%= article.body %></td>
    <td><%= link_to 'Show', article %></td>
    <td><%= link_to 'Edit', edit_article_path(article) %></td>
    <td><%= link_to 'Destroy', article, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Article', new_article_path %>

app/views/articles/new.html.erb
<h1>New article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @article.title %>
</p>

<p>
  <b>Body:</b>
  <%= @article.body %>
</p>


<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>

app/views/home/demo_console.html.erb
<h1>See javascript console in your browser for output</h1>

app/views/home/demo_raphael.html.erb
<div class="scheme-container">
	<div class="scheme-top-menu">
		<div class="top-menu-panel">
			<a href="#" onclick="add('resistor')" title="create a new resistor"><%= image_tag 'components/resistor.png' %></a>
			<a href="#" onclick="add('diode')" title="create a new diode"><%= image_tag 'components/diode.png' %></a>
			<a href="#" onclick="add('pnp_transistor')" title="create a new p-n-p transistor"><%= image_tag 'components/pnp_transistor.png' %></a>
			<a href="#" onclick="add('npn_transistor')" title="create a new n-p-n transistor"><%= image_tag 'components/npn_transistor.png' %></a>
			<a href="#" onclick="add('capacitor')" title="create a new capacitor"><%= image_tag 'components/capacitor.png' %></a>
			<a href="#" onclick="add('dc_source')" title="create a new DC source"><%= image_tag 'components/dc_source.png' %></a>
			<a href="#" onclick="add('wire')" title="create a new wire"><%= image_tag 'components/wire.png' %></a>
		</div>
		
		<div class="top-menu-panel">
			<a href="#" onclick="rotate_selected()" title="rotate selected component 90&deg; clockwise"><%= image_tag 'buttons/arrow-circle-225.png' %></a>
			<a href="#" onclick="remove_selected()" title="remove selected component"><%= image_tag 'buttons/cross-script.png' %></a>
		</div>
		
		
		<div class="top-menu-panel">
			<a href="#" onclick="reset_scheme()" title="stop any executions and reset components' states"><%= image_tag 'buttons/arrow-circle-double.png' %></a>
			<a href="#" onclick="simple_step()" title="step execution one component along"><%= image_tag 'buttons/arrow-repeat-once.png' %></a>
			<a href="#" onclick="full_step()" title="step execution all components at once"><%= image_tag 'buttons/arrow-repeat.png' %></a>
		</div>
		
		<div class="top-menu-panel">
			<em id="current-meter">
				<em href="#" id="current-title" title="Current on the selected pin">
					<%= image_tag 'buttons/dashboard.png' %>
				</em>
				
				<em id="current-i">
				</em>
				
				<em id="current-u">
				</em>
			</em>
		</div>
		
		<div class="top-menu-panel">
			<a href="javascript:save_scheme_svg();" title="View scheme as SVG">
				<%= image_tag 'buttons/eye.png' %>
			</a>
		</div>
	</div>

	<div id="scheme-holder"></div>
</div>

<div class="help-container">
	<div class="search-bar">
		<%= form_tag '/search', :method => 'get', :onsubmit => 'return article_search();' do %>
			<%= text_field_tag 'search-query' %>
			<%= submit_tag 'submit' %>
		<% end %>
	</div>
	
	<div class="help-panel">
	</div>
</div>

app/views/home/developers.html.erb
<p>
Keep calm and visit <a href="https://bitbucket.org/shybovycha/moochip">bitbucket</a> for updates 
<%= image_tag 'smilies/smiley-nerd.png' %>
</p>

app/views/home/index.html.erb
<h2>Let me introduce you...</h2>
<p>
	<em>What in the world is this?</em> - you'll probably ask when you first visit this website.<br />
	This is going to become an interactive electronics tutorial. If i will finish it, of course.<br />

	<br />

	<em>Interactive electronics tutorial? What's that?</em> See, when you do want to learn something,
	it's always better to see it in action than just read tons of text 'bout it. The same is true fofr electronics.
	It's really hard to understand the difference between <em>p-n-p</em> an <em>n-p-n</em> transistors when you
	did not even seen them before! For example, i did not understand that difference until i started this project 
	<%= image_tag 'smilies/smiley-razz.png' %><br />

	<br />

	<em>p-n-p? Transistor? Too many difficult words!</em> Just click in the menu "Let's start" above and dive
	into the world of electronics!
</p>

<h2>Oh, there's something missing...</h2>
<p>
	Yeah, this project is in an early development yet. I even do not know if i will be able to finish it!
	Still, this is only my coursework. A very, very pretty coursework <%= image_tag 'smilies/smiley-lol.png' %>
	So, don't  be upset! If i'll find the reason to add something to this project - i'll surely do it!
	Have fun! <%= image_tag 'smilies/smiley-wink.png' %>
</p>


<h2>What's gonna be clicked next?</h2>
<p>
	<em>Well, i see some strange pictures and light rectangle. So, what's next?</em> That rectangle is a 
	<em>scheme sheet</em>. It is the right place to create a schemes - a set of connected symbols,
	intertwined into a diabolic picture called <em>(electronic) circuit</em>. It shows the heretics
	called "engineers", which part should be connected to which parts and how the device will work at all.<br />

	<br />

	The rectangle with odd pictures above the sheet is the <em>toolbar</em>. It will become your mostly used
	part of the site (taking into account the fact you want to <strong>experiment</strong> mostly).
	It is divided into three parts:
	
	<ul>
		<li>
			<strong>the component container</strong> - the place, where all the components the system knows
			are located. They are represented by their <em>symbols</em> - that strange pictures
			as rectangles, triangles, circles and lines. Click on one of them and it will appear
			in the <em>top-left</em> corner of your sheet. Then you'll be able to operate with
			the component using your mouse and the edit panel.
		</li>
		
		<li>
			<strong>the edit panel</strong> - the one which allows you to rotate your components clockwise
			<%= image_tag 'buttons/arrow-circle-225.png' %> and remove the selected component and its
			connections from the sheet <%= image_tag 'buttons/cross-script.png' %>. You can select one
			of your components clicking on it with the left mouse button. To deselect component simply
			click somewhere on the sheet where no component is located.
		</li>
		
		<li>
			<strong>the run process controls</strong> - buttons, which start the magick are located here!
			They allow you to run all the scheme at once <%= image_tag 'buttons/arrow-repeat.png' %>, to step your run process
			one step along (e.g. to invoke the next "wave" of components) <%= image_tag 'buttons/arrow-repeat-once.png' %> or to
			reset all the scheme <%= image_tag 'buttons/arrow-circle-double.png' %> - to clean the execution component queue and reset each component
			states.
		</li>
	</ul>
	
	<br />
	
	<em>Now let's try to do something... Errr... How?</em> There are no tricks. User Interface (aka <em>UI</em>)
	is aimed to be as easy and user-friendly as possible. So, here's the list on how things are done:
	
	<table>
		<tr>
			<td>
				<strong>You want to...</strong>
			</td>
			
			<td>
				<strong>Follow these:</strong>
			</td>
		</tr>
		
		<tr>
			<td>
				Add a component to the sheet
			</td>
			
			<td>
				Click on the component's icon
			</td>
		</tr>
		
		<tr>
			<td>
				Drag the component over the sheet
			</td>
			
			<td>
				Press your left mouse button over the component. <strong>Do not unpress it yet!</strong>
				Move it with the component selected to the place you want. And now, unpress the left
				mouse button.
			</td>
		</tr>
		
		<tr>
			<td>
				Select the component
			</td>
			
			<td>
				Click left mouse button over the component on the sheet.
				When the dashed rectangle appears around the component - it is selected.
			</td>
		</tr>
		
		<tr>
			<td>
				Rotate the component
			</td>
			
			<td>
				Select the component and click the rotate button <%= image_tag 'buttons/arrow-circle-225.png' %> 
				in the toolbar above the sheet.
			</td>
		</tr>
		
		<tr>
			<td>
				Connect two components
			</td>
			
			<td>
				Move your mouse to the pin you want to connect with. The pin is a medium red circle
				near the component's symbol. When you've stopped your mouse cursor over the pin, the blue
				circle will appear around that pin showing that you selected that pin <br />
				<%= image_tag 'screens/pin-hover.jpg' %>
				<br />
				Now, press your left mouse button keeping mouse cursor over the pin, 
				<strong>do not unpress it yet</strong> and move a bit away from the pin - the blue dashed line will appear coming out of the selected pin and showing that you are trying to connect
				that pin to some other pin<br />
				<%= image_tag 'screens/pin-drag.jpg' %>
				<br />
				Move the cursor, <strong>keeping your left mouse button down</strong> to the pin
				you want connect to until the blue circle appears around that other pin. Only then
				you can release your left mouse button.<br />
				<%= image_tag 'screens/pin-connect.jpg' %>
				<br />
				The connection line will appear. It will automaticly create some bends.
				<%= image_tag 'screens/connection-line-created.jpg' %>
				<br />
			</td>
		</tr>

		<tr>
			<td>
				Edit connection
			</td>
			
			<td>
				Move your mouse to the connection line you want to edit. The connection line is the bended line which connects two component' pins. Usually it has dark color like black.
				Click on the connection line to select it.<br />
				<%= image_tag 'screens/connection-line-select.jpg' %>
				<br />
				The red rectangles will appear. They are <strong>base points</strong>. They determine where the connection line should follow. Connected together one-to-one and to the component' pins, they
				form a connection line. You can drag them to change the connection line<br />
				<%= image_tag 'screens/base-point-drag.jpg' %>
				<br />
				Connection line will be updated immediatly - it is a bit hard for your browser but more pretty. Yet it could be configured (simply run <em>MooChip.lightMode = true</em> within your JS console).<br />
				<%= image_tag 'screens/base-point-drop.jpg' %>
				<br />
				You can create base points double-clicking on the connection line.<br />
				<%= image_tag 'screens/base-point-create.jpg' %>
				<br />
				Base points are removed with double-clicking on them.<br />
				<%= image_tag 'screens/base-point-remove.jpg' %>
				<br />
			</td>
		</tr>

		<tr>
			<td>
				Remove single connection
			</td>
			
			<td>
				First of all, select the connection line you want to remove.<br />
				<%= image_tag 'screens/connection-line-select.jpg' %>
				<br />
				Then simply click the <em>Remove</em> button <%= image_tag 'buttons/cross-script.png' %> - and viola!
				<%= image_tag 'screens/connection-line-remove.jpg' %>
				<br />
			</td>
		</tr>
		
		<tr>
			<td>
				Remove component and its connections
			</td>
			
			<td>
				Select the component and click the remove button <%= image_tag 'buttons/cross-script.png' %>
				in the toolbar.<br />
				<%= image_tag 'screens/circuit-sample.jpg' %>
				<br />
				<%= image_tag 'screens/component-remove.jpg' %>
				<br />
			</td>
		</tr>

		<tr>
			<td>
				Cancel selection
			</td>
			
			<td>
				Click somewhere on the sheet where no connection lines, pins or components are located.<br />
				<%= image_tag 'screens/circuit-sample.jpg' %>
				<br />
			</td>
		</tr>
		
		<tr>
			<td>
				Run the simulation
			</td>
			
			<td>
				Connect <strong>DC Source</strong> component to the other components of your sheet
				and click the run the full circuit simulation button <%= image_tag 'buttons/arrow-repeat.png' %>
				in the toolbar. Components which were invoked in the simulation will be highlighted with
				light-blue color
				<br />
				<%= image_tag 'screens/full-circuit-step.jpg' %>
			</td>
		</tr>
		
		<tr>
			<td>
				Step the simulation by one iteration
			</td>
			
			<td>
				Click the step simulation button <%= image_tag 'buttons/arrow-repeat-once.png' %> in the toolbar
				<br />
				<%= image_tag 'screens/simple-step.jpg' %>
			</td>
		</tr>
		
		<tr>
			<td>
				Reset simulations
			</td>
			
			<td>
				Click the reset execution button <%= image_tag 'buttons/arrow-circle-double.png' %> in the 
				toolbar. Any invoked component will become uninvoked.
				<br />
				<%= image_tag 'screens/circuit-reset.jpg' %>
			</td>
		</tr>
	</table>
</p>

app/views/home/license.html.erb
<%= @license %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8" />

		<%= stylesheet_link_tag "application.css", :media => "all" %>
		
		<%= javascript_include_tag 'browser-detect.js' %>
		<%= javascript_include_tag 'jquery-1.7.2.js' %>
		
		<% if (@demo == 'console') then %>
			<title>Moochip - JS Console simulation</title>
			
			<%= javascript_include_tag 'moochip.js' %>
			<%= javascript_include_tag 'moochip-stdlib.js' %>
			<%= javascript_include_tag 'demo-console.js' %>
		<% elsif (@demo) then %>
			<title>Moochip - Simulator</title>
			
			<%= javascript_include_tag 'raphael.js' %>
			<%= javascript_include_tag 'moochip-raphael.js' %>
			<%= javascript_include_tag 'moochip-stdlib-raphael.js' %>
			<%= javascript_include_tag 'demo-raphael.js' %>
		<% else %>
			<title><%= (!@title.nil? and !@title.empty?) ? @title : "moochip" %></title>
		<% end %>
		
		<%= csrf_meta_tags %>
	</head>

	<body>
		<div class="navigation-menu">
			<ul>
				<li><a href="/">About</a></li>
				<li><a href="/demo-raphael">Let's start!</a></li>
				<li><a href="/developers">Developers</a></li>
			</ul>
		</div>
		
		<div class="content">
			<%= yield %>
		</div>
		
		<div class="footer">
			<p>
				<a rel="license" href="http://creativecommons.org/licenses/by-sa/3.0/"><img alt="Creative Commons License" style="border-width:0" src="http://i.creativecommons.org/l/by-sa/3.0/80x15.png" /></a><br />This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-sa/3.0/">Creative Commons Attribution-ShareAlike 3.0 Unported License</a>.
			</p>
			
			<p>
				Author: <a href="mailto:shybovycha@gmail.com">Artem Shoobovych</a>
			</p>
			
			<p>
				Latest version of this software, 0.1.98 (and later builds), could be retrieved at <a href="https://bitbucket.org/shybovycha/moochip">bitbucket</a>
			</p>
		</div>
		
		<!-- GoStats JavaScript Based Code -->
			<script type="text/javascript" src="http://gostats.com/js/counter.js"></script>
			<script type="text/javascript">_gos='c4.gostats.com';_goa=371855;
			_got=5;_goi=1;_gol='web stats hits';_GoStatsRun();</script>
			<noscript><a target="_blank" title="web stats hits" 
			href="http://gostats.com"><img alt="web stats hits" 
			src="http://c4.gostats.com/bin/count/a_371855/t_5/i_1/counter.png" 
			style="border-width:0" /></a></noscript>
		<!-- End GoStats JavaScript Based Code -->

	</body>
</html>